language: generic
sudo: false

cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/deps/boost-1.61.0"

addons:
  apt:
    packages:
      - g++-6
      - clang-3.6
      - cmake
      - cmake-data
    sources: &sources
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports

install:
  # Download Boost and copy the header files (We don't need the compiled libraries right now)
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    BOOST_VERSION=1.61.0
    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
        BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
        mkdir -p ${BOOST_DIR}
        { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
    fi
    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build
    - cd build
    - cmake .. ${CMAKE_OPTIONS} -DGLTFPP_BUILD_TESTS=1

script: make -j2 gltfpp_test && ctest .